[#ftl/]
[#-- @ftlvariable name="status" type="io.fusionauth.domain.reactor.ReactorStatus" --]
[#import "../../_utils/dialog.ftl" as dialog/]
[#import "../../_utils/message.ftl" as message/]
[#if status.breachedPasswordDetection == "ACTIVE" || status.breachedPasswordDetection == "DISCONNECTED"]
  [@dialog.confirm action="regenerate-key" key="warn"/]
[#else]
  [@dialog.view]
     [@message.print key="not-available"/]
  [/@dialog.view]
[/#if]
