[#ftl/]
[#-- @ftlvariable name="applicationId" type="java.util.UUID" --]
[#-- @ftlvariable name="application" type="io.fusionauth.domain.Application" --]
[#-- @ftlvariable name="applications" type="java.util.List<io.fusionauth.domain.Application>" --]
[#-- @ftlvariable name="canEditRoles" type="boolean" --]
[#-- @ftlvariable name="fields" type="java.util.Map<java.lang.Integer, java.util.List<io.fusionauth.domain.form.FormField>>" --]
[#-- @ftlvariable name="registration" type="io.fusionauth.domain.UserRegistration" --]
[#-- @ftlvariable name="user" type="io.fusionauth.domain.User" --]
[#-- @ftlvariable name="userId" type="java.util.UUID" --]
[#-- @ftlvariable name="groupNames" type="java.util.List<java.lang.String>" --]
[#-- @ftlvariable name="groupManagedRoles" type="boolean" --]
[#import "../../../_utils/button.ftl" as button/]
[#import "../../../_utils/helpers.ftl" as helpers/]
[#import "../../../_utils/message.ftl" as message/]
[#import "../../../_utils/properties.ftl" as properties/]

[#function generateSectionLabel sectionNumber aplicationId]
  [#--  Application specific, not application specific, then default --]
  [#local sectionLabel = theme.optionalMessage("[${aplicationId}]{registration-form-section}${sectionNumber}")/]
  [#local resolvedLabel = sectionLabel != "[${aplicationId}]{registration-form-section}${sectionNumber}"/]
  [#if !resolvedLabel]
    [#local sectionLabel = theme.optionalMessage("{registration-form-section}${sectionNumber}")/]
    [#local resolvedLabel = sectionLabel != "{registration-form-section}${sectionNumber}"/]
  [/#if]
  [#if !resolvedLabel]
    [#if sectionNumber > 1]
      [#return '${message.inline("registration-form-section")} ${sectionNumber}'/]
    [#else]
      [#return ""/]
    [/#if]
  [#else]
    [#return sectionLabel /]
  [/#if]
[/#function]

[#macro formFields action]

  [#-- On an add registration, select the application first --]
  [#if action == "add" && !applicationId??]
    <fieldset>
      [@control.hidden name="userId"/]
      [@control.hidden name="tenantId"/]
      [@control.select name="registration.applicationId" labelKey="application" items=applications textExpr="name" valueExpr="id" required=true headerL10n="selection-required" headerValue="" tooltip=function.message('{tooltip}application')/]
    </fieldset>
    [#return/]
  [/#if]

  [#local openFieldSet = true/]
  <fieldset>
    [@control.text name="" labelKey="application" value="${application.name}" disabled=true tooltip=function.message('{tooltip}readOnly')/]
    [#if action != "add"]
      [@control.text name="" labelKey="id" value="${registration.id}" disabled=true tooltip=function.message('{tooltip}readOnly')/]
    [/#if]
    [@control.text name="" labelKey="email" value="${properties.display(user, 'email')}" disabled=true tooltip=function.message('{tooltip}readOnly')/]
    [@control.text name="" labelKey="user-id" value="${user.id}" disabled=true tooltip=function.message('{tooltip}readOnly')/]
    [@control.hidden name="applicationId"/]
    [@control.hidden name="registration.applicationId"/]

    [#if groupManagedRoles]
      [@message.alertColumn message=function.message('group.managedRoles.info', properties.join(groupNames)) type="info" icon="info-circle"/]
    [/#if]
    [@control.hidden name="userId"/]
    [@control.hidden name="tenantId"/]

    [#list fields as fieldKey, fieldValues]
      [#if openFieldSet]
        </fieldset>
        [#local openFieldSet = false/]
      [/#if]
      <fieldset>
      [#local sectionNumber = fieldKey + 1/]
      [#local sectionLabel = generateSectionLabel(sectionNumber applicationId) /]
      [#if sectionLabel?has_content]
      <legend> ${sectionLabel} </legend>
      [/#if]

      [#-- If you're editing yourself provide a description of how the language and timezone can be used in the FusionAuth UI --]
      [#local showLocalEditInfo = false]
      [#if action == "edit" && ftlCurrentUser.id == userId && registration.applicationId?? && registration.applicationId == fusionAuth.statics['io.fusionauth.domain.Application'].FUSIONAUTH_APP_ID]
        [#list fieldValues as fieldValue]
          [#if fieldValue.key == "registration.timezone" || fieldValue.key == "registration.preferredLanguages"]
            [#local showLocalEditInfo = true]
            [#break]
          [/#if]
        [/#list]
      [/#if]

      [#if showLocalEditInfo ]
        <p><em>[@message.print key="{description}fusionauth-registration"/]</em></p>
      [/#if]

      [#list fieldValues as fieldValue]
        [#local fieldIsReadOnly = helpers.isFieldReadOnly(fieldValue, action, (ftlCurrentUser.id == userId!''))/]
        [@helpers.customField fieldValue fieldValue.confirm fieldValue?is_first fieldIsReadOnly action/]
      [/#list]
    [/#list]
  </fieldset>
[/#macro]
