development:
  FUSION_AUTH_CLIENT_ID: e4bc44b7-feed-4f73-93d8-a966dcffa200
  FUSION_AUTH_CLIENT_SECRET: 6HC7j14y0l9unmKabtvtB0Mj5KfFU7aNjYdEnqBRDjw
  WEBSITE_URL: https://d790-2401-4900-1c67-7578-4cf4-35d6-9225-95d9.ngrok-free.app
  FUSION_AUTH_APPLICATION_URL: http://localhost:9011
  FUSIONAUTH_TENANT_ID: 5fb699ef-f22d-46c5-9d2a-0289ee7bbe7e
  AUTHORIZATION: Z788oDfRiOGYi9sd6VlrCcywceZxwFInltb7aSVQI7LWYHqavId0apfl
  TOKEN: /yh5FZFA32Au2Rijp06z9Xb2btRnu70Nbf8RV+qviS0=

